### ISSUE TITLE
Ready data unknown function vlpbek()

### ISSUE THREAD

**Issue by Fraukje** [ed2c/wisselstroom_demo#2]
Hello!
I'm trying to run demo_kort.qmd and the first problem I encountered was an unknown function 'read_vlpbek_data()' (line 32), but I was able to find in the documentation of the wisselstroom package that this should probably be 'read_bek_data()'. However, the next line (33) contains function 'vlpbek()': where can I find this? @MMJansen

**Comment by MMJansen** [comment]
Hi Fraukje! Nice you are interested in the package! The functions in the package wisselstroom have changed, and I still have to update the demo project. Working now on the vignettes, and hopefully sunday the demo project is up to date again.

**Comment by MMJansen** [comment]
Hi Fraukje, the scripts are updated. The function that was before `vlpbek()` is now `make_flow_basics()`.

**Comment by Fraukje** [comment]
Whew, I am very impressed with how fast you resolved this issue @MMJansen. I just retried running the demo and it all works smoothly now, thanks!
